name: Rust - Build and Test (Multi-Project)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          component: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check format
        run: cargo fmt -- --check

      - name: Build
        run: cargo build --locked --verbose


      - name: Build child projects
        run: |
          for project in $(find . -type d -name 'Cargo.toml' | grep -v './' | sort); do
            cargo build --verbose --manifest-path "$project";
          done

  test:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the successful completion of the 'build' job
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          component: rustfmt, clippy

      - name: Run tests (child projects)
        run: |
          for project in $(find . -type d -name 'Cargo.toml' | grep -v './' | sort); do
            cargo test --verbose --manifest-path "$project";
          done
